### ISSUE TITLE
Can it use integrated GPU?

### ISSUE THREAD

**Issue by abhijitxp01** [suno-ai/bark#132] opened 2023-04-25 09:32 UTC
I've  AMD integrated GPU 4GB, but it's still showing **"No GPU being used. Careful, inference might be extremely slow!"**

Does this program not use integrated GPU?

**Comment by Advitica** [comment] 2023-04-25 12:03
It's looking for Nvidia and CUDA installed.  I have multiple GPU's with 6GB but this is not enough to load the model :(

**Comment by gkucsko** [comment] 2023-04-25 14:25
have you tried using small versions of model (specified in preload_models?)
not sure about amd support, right now only cuda and cpu are supported

**Comment by gkucsko** [comment] 2023-04-26 01:32
are the issues here related? is everyone on AMD or is this mixed with cuda issues?

**Comment by abhijitxp01** [comment] 2023-04-26 09:19
So it will not work until I use the Nvidia Graphics card!

**Comment by gkucsko** [comment] 2023-04-26 13:10
it should work on cpu, albeit slower of course..

**Comment by limapedro** [comment] 2023-04-26 15:16
> 

how to run on cpu? it doesn't seem to have a option to pass device on init of the model!

**Comment by gkucsko** [comment] 2023-04-26 22:52
`preload_models` has arguments to disable gpu, but either way it should happen automatically if you don't have a supported gpu

**Comment by gkucsko** [comment] 2023-04-27 13:19
Closing for now since I can’t reproduce the issue

**Closed by gkucsko** 2023-04-27 13:19 UTC
