### ISSUE TITLE
How to download all models at once at the beginning on colab?

### ISSUE THREAD

**Issue by remybonnav** [suno-ai/bark#49] opened 2023-04-22 10:34 UTC
There are many models downloaded during inference which is really annoying, can't we just have a download of all models at the beginning?

**Comment by khimaros** [comment] 2023-04-22 21:17
duplicate of https://github.com/suno-ai/bark/issues/46

**Closed** 2023-04-22 21:24 UTC

**Comment by gkucsko** [comment] 2023-04-22 21:33
you can use: `preload_models()`
