### ISSUE TITLE
Can not find bark anywhere after install

### ISSUE THREAD

**Issue by indianninja2018** [suno-ai/bark#45] opened 2023-04-22 03:45 UTC
I installed using the single line command after opening cmd in E/bark:
pip install git+https://github.com/suno-ai/bark.git
 and then the directory I used E/bark was empty. Where is it?

**Comment by angryfarmersmith** [comment] 2023-04-22 04:46
you just install a python moudel. you need to create a python file and import it. try to copy the code in the usage and save it as test.py and run it in the command line.

**Comment by indianninja2018** [comment] 2023-04-22 05:38
So i have basically installed it with python, right? I will create a bark.py or something and can run with cmd, and that should work? Dont I need to download models? I am very noob at this, can you tell me how to import the bark.py and run it? Please?

**Comment by BSalita** [comment] 2023-04-24 14:24
bark is a new project so expect to be bitten. Yes, you should create a filename but not bark.py because that's the one filename which conflicts with bark namespace. Use something like demo.py instead. You don't need to download models because it will be done automatically when you run demo.py.

To the authors:
1. People will want to use bark.py. Isn't there someway to avoid the namespace conflict?
2. Place a file (README, demo.py) into the project directory so people aren't confused by the empty directory.

**Comment by gkucsko** [comment] 2023-04-26 01:41
not sure i understand what the issue is to be honest. closing for now, feel free to reopen if issue persists

**Closed by gkucsko** 2023-04-26 01:41 UTC

**Comment by keetruda69** [comment] 2023-06-20 09:22
If you have virtual env, looks there, e.g: \virutalenv\env\lib\site-packages\bark\api.py"
