### ISSUE TITLE
HTTPSConnectionPool Error when downloading model 

### ISSUE THREAD

**Issue by albertshao** [suno-ai/bark#263] opened 2023-05-07 14:58 UTC
In most cases, when downloading the mode completed about 30% (703M/2.32G [08:57<14:32, 1.85MB/s]), it raised the following error no matter which one is performed. use_small_models_on_cpu.ipynb or long_form_generation.ipynb. 

ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

Laptop: 
MacBook Pro (16-inch, 2021)
Chip: Apple M1 Pro

**Comment by gkucsko** [comment] 2023-05-07 23:28
gonna close this for now as duplicate of https://github.com/suno-ai/bark/discussions/251
that way we can consolidate discussion

**Closed by gkucsko** 2023-05-07 23:28 UTC
