### ISSUE TITLE
Datas accountability 

### ISSUE THREAD

**Issue by sarahcpoirier** [suno-ai/bark#293] opened 2023-05-15 02:20 UTC
Hi! Love the model. Can you tell me about your data sets? How were the voices collected? Thank you!

**Comment by adriens** [comment] 2023-05-15 02:48
I may even add : do you have a guide for dummies to create custom voices ?

**Comment by gkucsko** [comment] 2023-05-15 23:19
closing as duplicate of https://github.com/suno-ai/bark/issues/2

**Closed by gkucsko** 2023-05-15 23:19 UTC
