### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by baroninn** [suno-ai/bark#180] opened 2023-04-27 09:12 UTC
Hi,
How can I train a new language ?
I would really like to add Icelandic to this.

thank you

**Comment by gkucsko** [comment] 2023-04-27 12:05
closing as duplicate of https://github.com/suno-ai/bark/issues/37
for suggestions on language support please post here: https://github.com/suno-ai/bark/discussions/111

**Closed by gkucsko** 2023-04-27 12:05 UTC
