### ISSUE TITLE
EnCodec allows commercial use - new license

### ISSUE THREAD

**Issue by ryanloney** [suno-ai/bark#201] opened 2023-04-28 14:33 UTC
Can you update README and license now that Facebook Research updated their EnCodec model license to allow commercial use? It's now under MIT license. https://github.com/facebookresearch/encodec/commit/349b72939f57cb3bc7b60906c0ee8228c849485d

The README states that Suno models can be used for commercial purposes but EnCodec cannot. 

Thank you!

-Ryan

**Comment by gkucsko** [comment] 2023-04-28 20:32
thanks yup working on it. closing for now as duplicate of https://github.com/suno-ai/bark/issues/179

**Closed by gkucsko** 2023-04-28 20:32 UTC
